<!DOCTYPE html>
<html lang="en"><head>
<script src="lec-07a-multiple-linear-regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="lec-07a-multiple-linear-regression_files/libs/quarto-html/tabby.min.js"></script>
<script src="lec-07a-multiple-linear-regression_files/libs/quarto-html/popper.min.js"></script>
<script src="lec-07a-multiple-linear-regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lec-07a-multiple-linear-regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lec-07a-multiple-linear-regression_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lec-07a-multiple-linear-regression_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="CSUCI - Dr.&nbsp;Catalina Medina">
  <title>Data 308: Lecture 7a</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lec-07a-multiple-linear-regression_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lec-07a-multiple-linear-regression_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="lec-07a-multiple-linear-regression_files/libs/revealjs/dist/theme/quarto-c99231f18bc440273635742d2c598c24.css">
  <link href="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Data 308: Lecture 7a</h1>
  <p class="subtitle">Multiple Linear Regression &amp; Categorical Predictors (ISL 3.2.1 &amp; 3.3.1)</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
CSUCI - Dr.&nbsp;Catalina Medina
</div>
</div>
</div>

</section>
<section id="simple-verusus-multiple" class="slide level2">
<h2>Simple verusus Multiple</h2>
<p><strong>Simple linear regression</strong> involves regressing <span class="math inline">\(Y\)</span> on only one <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\]</span></p>
<p><strong>Multiple linear regression</strong> involves regressing <span class="math inline">\(Y\)</span> on multiple <span class="math inline">\(X\)</span>’s</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + ... + \beta_p X_{pi} + \epsilon_i.\]</span></p>
<div class="fragment">
<p><em>Why would we want multiple</em> <span class="math inline">\(X\)</span>’s?</p>
</div>
</section>
<section id="motivating-example-loan-data" class="slide level2">
<h2>Motivating example: Loan data</h2>
<p>This dataset represents thousands of loans made through the Lending Club platform, which is a platform that allows individuals to lend to other individuals.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-label="1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb1-2"><a href="" aria-label="2"></a></span>
<span id="cb1-3"><a href="" aria-label="3"></a><span class="fu">data</span>(<span class="st">"loans_full_schema"</span>)</span>
<span id="cb1-4"><a href="" aria-label="4"></a></span>
<span id="cb1-5"><a href="" aria-label="5"></a><span class="co"># Data wrangling and saving clean data into `loans`</span></span>
<span id="cb1-6"><a href="" aria-label="6"></a>loans <span class="ot">&lt;-</span> loans_full_schema <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="" aria-label="7"></a>  <span class="fu">mutate</span>(<span class="at">bankruptcy =</span> public_record_bankrupt <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-8"><a href="" aria-label="8"></a>  <span class="fu">mutate</span>(<span class="at">credit_util =</span> total_credit_utilized <span class="sc">/</span> total_credit_limit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="motivating-example-loan-data-1" class="slide level2">
<h2>Motivating example: Loan data</h2>
<p>You can type <code>? loans_full_schema</code> into Console for the full data documentation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-label="1"></a><span class="fu">glimpse</span>(loans)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 10,000
Columns: 57
$ emp_title                        &lt;chr&gt; "global config engineer ", "warehouse…
$ emp_length                       &lt;dbl&gt; 3, 10, 3, 1, 10, NA, 10, 10, 10, 3, 1…
$ state                            &lt;fct&gt; NJ, HI, WI, PA, CA, KY, MI, AZ, NV, I…
$ homeownership                    &lt;fct&gt; MORTGAGE, RENT, RENT, RENT, RENT, OWN…
$ annual_income                    &lt;dbl&gt; 90000, 40000, 40000, 30000, 35000, 34…
$ verified_income                  &lt;fct&gt; Verified, Not Verified, Source Verifi…
$ debt_to_income                   &lt;dbl&gt; 18.01, 5.04, 21.15, 10.16, 57.96, 6.4…
$ annual_income_joint              &lt;dbl&gt; NA, NA, NA, NA, 57000, NA, 155000, NA…
$ verification_income_joint        &lt;fct&gt; , , , , Verified, , Not Verified, , ,…
$ debt_to_income_joint             &lt;dbl&gt; NA, NA, NA, NA, 37.66, NA, 13.12, NA,…
$ delinq_2y                        &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0…
$ months_since_last_delinq         &lt;int&gt; 38, NA, 28, NA, NA, 3, NA, 19, 18, NA…
$ earliest_credit_line             &lt;dbl&gt; 2001, 1996, 2006, 2007, 2008, 1990, 2…
$ inquiries_last_12m               &lt;int&gt; 6, 1, 4, 0, 7, 6, 1, 1, 3, 0, 4, 4, 8…
$ total_credit_lines               &lt;int&gt; 28, 30, 31, 4, 22, 32, 12, 30, 35, 9,…
$ open_credit_lines                &lt;int&gt; 10, 14, 10, 4, 16, 12, 10, 15, 21, 6,…
$ total_credit_limit               &lt;int&gt; 70795, 28800, 24193, 25400, 69839, 42…
$ total_credit_utilized            &lt;int&gt; 38767, 4321, 16000, 4997, 52722, 3898…
$ num_collections_last_12m         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ num_historical_failed_to_pay     &lt;int&gt; 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0…
$ months_since_90d_late            &lt;int&gt; 38, NA, 28, NA, NA, 60, NA, 71, 18, N…
$ current_accounts_delinq          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ total_collection_amount_ever     &lt;int&gt; 1250, 0, 432, 0, 0, 0, 0, 0, 0, 0, 0,…
$ current_installment_accounts     &lt;int&gt; 2, 0, 1, 1, 1, 0, 2, 2, 6, 1, 2, 1, 2…
$ accounts_opened_24m              &lt;int&gt; 5, 11, 13, 1, 6, 2, 1, 4, 10, 5, 6, 7…
$ months_since_last_credit_inquiry &lt;int&gt; 5, 8, 7, 15, 4, 5, 9, 7, 4, 17, 3, 4,…
$ num_satisfactory_accounts        &lt;int&gt; 10, 14, 10, 4, 16, 12, 10, 15, 21, 6,…
$ num_accounts_120d_past_due       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, NA, 0, 0, 0, 0, …
$ num_accounts_30d_past_due        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ num_active_debit_accounts        &lt;int&gt; 2, 3, 3, 2, 10, 1, 3, 5, 11, 3, 2, 2,…
$ total_debit_limit                &lt;int&gt; 11100, 16500, 4300, 19400, 32700, 272…
$ num_total_cc_accounts            &lt;int&gt; 14, 24, 14, 3, 20, 27, 8, 16, 19, 7, …
$ num_open_cc_accounts             &lt;int&gt; 8, 14, 8, 3, 15, 12, 7, 12, 14, 5, 8,…
$ num_cc_carrying_balance          &lt;int&gt; 6, 4, 6, 2, 13, 5, 6, 10, 14, 3, 5, 3…
$ num_mort_accounts                &lt;int&gt; 1, 0, 0, 0, 0, 3, 2, 7, 2, 0, 2, 3, 3…
$ account_never_delinq_percent     &lt;dbl&gt; 92.9, 100.0, 93.5, 100.0, 100.0, 78.1…
$ tax_liens                        &lt;int&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ public_record_bankrupt           &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0…
$ loan_purpose                     &lt;fct&gt; moving, debt_consolidation, other, de…
$ application_type                 &lt;fct&gt; individual, individual, individual, i…
$ loan_amount                      &lt;int&gt; 28000, 5000, 2000, 21600, 23000, 5000…
$ term                             &lt;dbl&gt; 60, 36, 36, 36, 36, 36, 60, 60, 36, 3…
$ interest_rate                    &lt;dbl&gt; 14.07, 12.61, 17.09, 6.72, 14.07, 6.7…
$ installment                      &lt;dbl&gt; 652.53, 167.54, 71.40, 664.19, 786.87…
$ grade                            &lt;fct&gt; C, C, D, A, C, A, C, B, C, A, C, B, C…
$ sub_grade                        &lt;fct&gt; C3, C1, D1, A3, C3, A3, C2, B5, C2, A…
$ issue_month                      &lt;fct&gt; Mar-2018, Feb-2018, Feb-2018, Jan-201…
$ loan_status                      &lt;fct&gt; Current, Current, Current, Current, C…
$ initial_listing_status           &lt;fct&gt; whole, whole, fractional, whole, whol…
$ disbursement_method              &lt;fct&gt; Cash, Cash, Cash, Cash, Cash, Cash, C…
$ balance                          &lt;dbl&gt; 27015.86, 4651.37, 1824.63, 18853.26,…
$ paid_total                       &lt;dbl&gt; 1999.330, 499.120, 281.800, 3312.890,…
$ paid_principal                   &lt;dbl&gt; 984.14, 348.63, 175.37, 2746.74, 1569…
$ paid_interest                    &lt;dbl&gt; 1015.19, 150.49, 106.43, 566.15, 754.…
$ paid_late_fees                   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ bankruptcy                       &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, FAL…
$ credit_util                      &lt;dbl&gt; 0.54759517, 0.15003472, 0.66134832, 0…</code></pre>
</div>
</div>
</section>
<section id="motivating-example-loan-data-2" class="slide level2">
<h2>Motivating example: Loan data</h2>
<ul>
<li><code>interest_rate</code> Interest rate on the loan, in an annual percentage.</li>
<li><code>bankruptcy</code> An indicator variable for whether the borrower has a past bankruptcy in their record. This variable takes a value of <code>1</code> if the answer is <em>yes</em> and <code>0</code> if the answer is <em>no</em>.</li>
<li><code>verified_income</code> Categorical variable describing whether the borrower’s income source and amount have been verified, with levels <code>Verified</code> (source and amount verified), <code>Source Verified</code> (source only verified), and <code>Not Verified</code>.</li>
</ul>
<!-- ## Motivating example: Loan data -->
<!-- - `credit_util`    Of all the credit available to the borrower, what fraction are they utilizing. For example, the credit utilization on a credit card would be the card's balance divided by the card's credit limit. -->
<!-- - `debt_to_income` Debt-to-income ratio, which is the percentage of total debt of the borrower divided by their total income. -->
<!-- - `term`   The length of the loan, in months. -->
<!-- ## Motivating example: Loan data -->
<!-- - `issue_month`    The month and year the loan was issued, which for these loans is always during the first quarter of 2018. -->
<!-- - `credit_checks`  Number of credit checks in the last 12 months. For example, when filing an application for a credit card, it is common for the company receiving the application to run a credit check. -->
</section>
<section>
<section id="categorical-explanatory-variables" class="title-slide slide level1 center">
<h1>Categorical explanatory variables</h1>

</section>
<section id="regressing-interest-rate-on-bankruptcy" class="slide level2">
<h2>Regressing interest rate on bankruptcy</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-label="1"></a><span class="fu">count</span>(loans, bankruptcy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  bankruptcy     n
  &lt;lgl&gt;      &lt;int&gt;
1 FALSE       8785
2 TRUE        1215</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(loans, <span class="fu">aes</span>(<span class="at">x =</span> bankruptcy, <span class="at">y =</span> interest_rate)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="" aria-label="2"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-1" class="slide level2">
<h2>Regressing interest rate on bankruptcy</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="" aria-label="1"></a>rate_on_bankruptcy_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(interest_rate <span class="sc">~</span> bankruptcy, <span class="at">data =</span> loans)</span>
<span id="cb7-2"><a href="" aria-label="2"></a></span>
<span id="cb7-3"><a href="" aria-label="3"></a><span class="fu">summary</span>(rate_on_bankruptcy_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = interest_rate ~ bankruptcy, data = loans)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7648 -3.6448 -0.4548  2.7120 18.6020 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     12.3380     0.0533 231.490  &lt; 2e-16 ***
bankruptcyTRUE   0.7368     0.1529   4.819 1.47e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.996 on 9998 degrees of freedom
Multiple R-squared:  0.002317,  Adjusted R-squared:  0.002217 
F-statistic: 23.22 on 1 and 9998 DF,  p-value: 1.467e-06</code></pre>
</div>
</div>
<div class="fragment">
<p><em>How do we interpret the slope? What does it mean to be one unit more for X?</em></p>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-fitted-model" class="slide level2">
<h2>Regressing interest rate on bankruptcy: Fitted model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="" aria-label="1"></a><span class="fu">library</span>(broom)</span>
<span id="cb9-2"><a href="" aria-label="2"></a></span>
<span id="cb9-3"><a href="" aria-label="3"></a><span class="fu">tidy</span>(rate_on_bankruptcy_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term           estimate std.error statistic    p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 (Intercept)      12.3      0.0533    231.   0         
2 bankruptcyTRUE    0.737    0.153       4.82 0.00000147</code></pre>
</div>
</div>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.34</p>
<p><span class="math inline">\(+\)</span> 0.74 * <span class="math inline">\(I(\text{Bankruptcy}_i = \text{TRUE})\)</span></p>
</section>
<section id="regressing-interest-rate-on-bankruptcy-interpreting-coefficients" class="slide level2">
<h2>Regressing interest rate on bankruptcy: Interpreting coefficients</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.34</p>
<p><span class="math inline">\(+\)</span> 0.74 * <span class="math inline">\(I(\text{Bankruptcy}_i = \text{TRUE})\)</span></p>
<div class="fragment">
<p>Definition:</p>
<p><span class="math inline">\(I(\text{Bankruptcy}_i = \text{TRUE})\)</span> is an indicator variable.</p>
<ul>
<li>It will be equal to 0 if the condition is not met</li>
<li>It will be equal to 1 if the condition is met</li>
</ul>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-interpreting-coefficients-1" class="slide level2">
<h2>Regressing interest rate on bankruptcy: Interpreting coefficients</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.34</p>
<p><span class="math inline">\(+\)</span> 0.74 * <span class="math inline">\(I(\text{Bankruptcy}_i = \text{TRUE})\)</span></p>
<div class="fragment">
<ul>
<li><p>Expected interest rate for people with no bankruptcy on their record is 12.34.</p></li>
<li><p>Expected interest rate for people with at least one bankruptcy on their record is 12.34 + 0.74 = 13.08.</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>We estimate a 0.74% higher interest rate, on average, for borrowers with a bankruptcy on their record.</li>
</ul>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-2" class="slide level2">
<h2>Regressing interest rate on bankruptcy</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="t-test-versus-regression" class="slide level2">
<h2>t-test versus regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-label="1"></a>interest_rate_bankruptcy_false <span class="ot">&lt;-</span> loans <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="" aria-label="2"></a>  <span class="fu">filter</span>(bankruptcy <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="" aria-label="3"></a>  <span class="fu">pull</span>(interest_rate)</span>
<span id="cb11-4"><a href="" aria-label="4"></a></span>
<span id="cb11-5"><a href="" aria-label="5"></a>interest_rate_bankruptcy_true <span class="ot">&lt;-</span> loans <span class="sc">|&gt;</span> </span>
<span id="cb11-6"><a href="" aria-label="6"></a>  <span class="fu">filter</span>(bankruptcy <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb11-7"><a href="" aria-label="7"></a>  <span class="fu">pull</span>(interest_rate)</span>
<span id="cb11-8"><a href="" aria-label="8"></a></span>
<span id="cb11-9"><a href="" aria-label="9"></a><span class="fu">t.test</span>(interest_rate_bankruptcy_false, interest_rate_bankruptcy_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  interest_rate_bankruptcy_false and interest_rate_bankruptcy_true
t = -4.9599, df = 1598.6, p-value = 7.803e-07
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.0281548 -0.4454164
sample estimates:
mean of x mean of y 
 12.33800  13.07479 </code></pre>
</div>
</div>
</section>
<section id="t-test-versus-regression-1" class="slide level2">
<h2>t-test versus regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="" aria-label="1"></a><span class="fu">t.test</span>(interest_rate_bankruptcy_false, interest_rate_bankruptcy_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  interest_rate_bankruptcy_false and interest_rate_bankruptcy_true
t = -4.9599, df = 1598.6, p-value = 7.803e-07
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.0281548 -0.4454164
sample estimates:
mean of x mean of y 
 12.33800  13.07479 </code></pre>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-label="1"></a><span class="fu">tidy</span>(rate_on_bankruptcy_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term           estimate std.error statistic    p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 (Intercept)      12.3      0.0533    231.   0         
2 bankruptcyTRUE    0.737    0.153       4.82 0.00000147</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p>They are the same!</p>
</div>
</section>
<section id="regressing-on-categorical-predictors" class="slide level2">
<h2>Regressing on categorical predictors</h2>
<p>That was a continuous variable regression on a categorical variable with two levels (possibilities).</p>
<ul>
<li>Equivalent to a t-test.</li>
<li>Our regression line is really two flat lines (means)</li>
</ul>
<p>What if we regressed on a categorical variable with three or more levels (possibilities)?</p>
</section>
<section id="regressing-interest-rate-on-verified-income" class="slide level2">
<h2>Regressing interest rate on verified income</h2>
<p>Notice that the <code>verified_income</code> variable is categorical with three levels</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-label="1"></a><span class="fu">count</span>(loans, verified_income)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  verified_income     n
  &lt;fct&gt;           &lt;int&gt;
1 Not Verified     3594
2 Source Verified  4116
3 Verified         2290</code></pre>
</div>
</div>
</section>
<section id="section" class="slide level2">
<h2></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(loans, <span class="fu">aes</span>(<span class="at">x =</span> verified_income, <span class="at">y =</span> interest_rate)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="" aria-label="2"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regressing-interest-rate-on-verified-income-1" class="slide level2">
<h2>Regressing interest rate on verified income</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="" aria-label="1"></a>rate_on_verification <span class="ot">&lt;-</span> <span class="fu">lm</span>(interest_rate <span class="sc">~</span> verified_income, <span class="at">data =</span> loans)</span>
<span id="cb20-2"><a href="" aria-label="2"></a></span>
<span id="cb20-3"><a href="" aria-label="3"></a><span class="fu">summary</span>(rate_on_verification)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = interest_rate ~ verified_income, data = loans)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.0437 -3.7495 -0.6795  2.5345 19.6905 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    11.09946    0.08091  137.18   &lt;2e-16 ***
verified_incomeSource Verified  1.41602    0.11074   12.79   &lt;2e-16 ***
verified_incomeVerified         3.25429    0.12970   25.09   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.851 on 9997 degrees of freedom
Multiple R-squared:  0.05945,   Adjusted R-squared:  0.05926 
F-statistic: 315.9 on 2 and 9997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="fitted-interest-rate-model-fitted-model" class="slide level2">
<h2>Fitted interest rate model: Fitted model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="" aria-label="1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(rate_on_verification)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                           estimate std.error statistic   p.value
  &lt;chr&gt;                             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                       11.1     0.0809     137.  0        
2 verified_incomeSource Verified     1.42    0.111       12.8 3.79e- 37
3 verified_incomeVerified            3.25    0.130       25.1 8.61e-135</code></pre>
</div>
</div>
<p>Our model appears to be</p>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> =11.1</p>
<p>+ 1.42 <span class="math inline">\(I(\text{verified_income}_i = \text{Source Verified})\)</span></p>
<p>+ 3.25 <span class="math inline">\(I(\text{verified_income}_i = \text{Verified}).\)</span></p>
<div class="fragment">
<p><em>Is anything missing?</em></p>
</div>
</section>
<section id="categorical-predictors" class="slide level2">
<h2>Categorical predictors</h2>
<p>When fitting a regression model with a categorical variable that has <span class="math inline">\(k\)</span> levels where <span class="math inline">\(k \geq  2\)</span>, software will provide a coefficient for <span class="math inline">\(k-1\)</span> of those levels.</p>
<ul>
<li>For the last level that does not receive a coefficient, this is the <strong>reference level</strong>, and the coefficients listed for the other levels are all considered relative to this reference level.</li>
</ul>
</section>
<section id="expected-difference-in-interest-rate" class="slide level2">
<h2>Expected difference in interest rate</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> =11.1</p>
<p>+ 1.42 <span class="math inline">\(I(\text{verified_income}_i = \text{Source Verified})\)</span></p>
<p>+ 3.25 <span class="math inline">\(I(\text{verified_income}_i = \text{Verified}).\)</span></p>
<ul>
<li>We estimate a 1.42% higher interest rate, on average, for people source only verified relative to unverified people.</li>
<li>We estimate a 3.25% higher interest rate, on average, for people source and amount verified relative to unverified people.</li>
</ul>
</section>
<section id="expected-interest-rate" class="slide level2">
<h2>Expected interest rate</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> =11.1</p>
<p>+ 1.42 <span class="math inline">\(I(\text{verified_income}_i = \text{Source Verified})\)</span></p>
<p>+ 3.25 <span class="math inline">\(I(\text{verified_income}_i = \text{Verified}).\)</span></p>
<ul>
<li>We estimate the average interest rate for people not verified to be 11.1.</li>
<li>We estimate the average interest rate for people source only verified to be 12.52.</li>
<li>We estimate the average interest rate for people source and pay verified to be 15.77.</li>
</ul>
</section>
<section id="expected-interest-rate-1" class="slide level2">
<h2>Expected interest rate</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-18-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="converting-categorical-variables-to-numeric-in-regression" class="slide level2">
<h2>Converting categorical variables to numeric in regression</h2>
<p><em>Why shouldn’t we just convert the <code>verified_income</code> variable to a numeric?</em></p>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="" aria-label="1"></a>loans <span class="ot">&lt;-</span> loans <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="" aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">verified_income_numeric =</span> <span class="fu">case_when</span>(</span>
<span id="cb24-3"><a href="" aria-label="3"></a>    verified_income <span class="sc">==</span> <span class="st">"Not Verified"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb24-4"><a href="" aria-label="4"></a>    verified_income <span class="sc">==</span> <span class="st">"Source Verified"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb24-5"><a href="" aria-label="5"></a>    verified_income <span class="sc">==</span> <span class="st">"Verified"</span> <span class="sc">~</span> <span class="dv">2</span></span>
<span id="cb24-6"><a href="" aria-label="6"></a>  ))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="converting-categorical-variables-to-numeric-in-regression-1" class="slide level2">
<h2>Converting categorical variables to numeric in regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="" aria-label="1"></a>rate_on_ver_num_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(interest_rate <span class="sc">~</span> verified_income_numeric, <span class="at">data =</span> loans)</span>
<span id="cb25-2"><a href="" aria-label="2"></a></span>
<span id="cb25-3"><a href="" aria-label="3"></a><span class="fu">summary</span>(rate_on_ver_num_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = interest_rate ~ verified_income_numeric, data = loans)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.9344 -3.6798 -0.6544  2.5602 19.7602 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             11.02980    0.07395  149.15   &lt;2e-16 ***
verified_income_numeric  1.60731    0.06418   25.04   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.852 on 9998 degrees of freedom
Multiple R-squared:  0.05903,   Adjusted R-squared:  0.05893 
F-statistic: 627.2 on 1 and 9998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="converting-categorical-variables-to-numeric-in-regression-2" class="slide level2">
<h2>Converting categorical variables to numeric in regression</h2>
<p><span class="math inline">\(\hat{\beta_1} = 1.61\)</span></p>
<p>By converting we are implicitly assuming that there is a one unit difference between each of the levels:</p>
<ul>
<li>Not verified -&gt; Source only verified</li>
<li>Source only verified -&gt; Source and amount verified</li>
</ul>
<div class="fragment">
<p>This may not be the case, maybe “Source only verified” and “Source and amount verified” are more similar than “Not verified”</p>
</div>
<div class="fragment">
<p><strong>Not good practice!</strong></p>
</div>
</section></section>
<section>
<section id="multiple-predictors-of-different-variable-types" class="title-slide slide level1 center">
<h1>Multiple predictors of different variable types</h1>

</section>
<section id="regressing-interest-rate-on-bankruptcy-and-credit-lines" class="slide level2">
<h2>Regressing interest rate on bankruptcy and credit lines</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(loans, <span class="fu">aes</span>(<span class="at">x =</span> total_credit_lines, <span class="at">y =</span> interest_rate, <span class="at">color =</span> bankruptcy)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="" aria-label="2"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-21-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-and-credit-lines-1" class="slide level2">
<h2>Regressing interest rate on bankruptcy and credit lines</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="" aria-label="1"></a>rate_on_bank_and_credit_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(interest_rate <span class="sc">~</span> bankruptcy <span class="sc">+</span> total_credit_lines, <span class="at">data =</span> loans)</span>
<span id="cb28-2"><a href="" aria-label="2"></a></span>
<span id="cb28-3"><a href="" aria-label="3"></a><span class="fu">summary</span>(rate_on_bank_and_credit_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = interest_rate ~ bankruptcy + total_credit_lines, 
    data = loans)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.9651 -3.7041 -0.6226  2.7263 18.8697 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        12.762332   0.109102 116.976  &lt; 2e-16 ***
bankruptcyTRUE      0.737299   0.152762   4.826 1.41e-06 ***
total_credit_lines -0.018712   0.004199  -4.456 8.44e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.991 on 9997 degrees of freedom
Multiple R-squared:  0.004295,  Adjusted R-squared:  0.004095 
F-statistic: 21.56 on 2 and 9997 DF,  p-value: 4.54e-10</code></pre>
</div>
</div>
</section>
<section id="regressing-interest-rate-on-bankruptcy-and-credit-lines-2" class="slide level2">
<h2>Regressing interest rate on bankruptcy and credit lines</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-label="1"></a><span class="fu">tidy</span>(rate_on_bank_and_credit_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term               estimate std.error statistic    p.value
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 (Intercept)         12.8      0.109      117.   0         
2 bankruptcyTRUE       0.737    0.153        4.83 0.00000141
3 total_credit_lines  -0.0187   0.00420     -4.46 0.00000844</code></pre>
</div>
</div>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.76</p>
<p><span class="math inline">\(+\)</span> 0.74 <span class="math inline">\(I(\text{Banruptcy_i = TRUE})\)</span></p>
<p><span class="math inline">\(+\)</span> -0.02 <span class="math inline">\(\text{Number credit lines}_i\)</span></p>
</section>
<section id="interpreting-estimates" class="slide level2">
<h2>Interpreting estimates</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.76</p>
<p><span class="math inline">\(+\)</span> 0.74 <span class="math inline">\(I(\text{Banruptcy_i = TRUE})\)</span></p>
<p><span class="math inline">\(+\)</span> -0.02 <span class="math inline">\(\text{Number credit lines}_i\)</span></p>
<ul>
<li>We estimate an average interest rate of 12.76 for people with no bankruptcy and no lines of credit.</li>
</ul>
</section>
<section id="interpreting-estimates-1" class="slide level2">
<h2>Interpreting estimates</h2>
<p><span class="math inline">\(\hat{\text{Interest rate}}_i\)</span> = 12.76</p>
<p><span class="math inline">\(+\)</span> 0.74 <span class="math inline">\(I(\text{Banruptcy_i = TRUE})\)</span></p>
<p><span class="math inline">\(+\)</span> -0.02 <span class="math inline">\(\text{Number credit lines}_i\)</span></p>
<p>We interpret a slope <strong>with all other variables fixed</strong>:</p>
<ul>
<li>We estimate a 0.74% higher average interest rate for borrowers with a bankruptcy on their record, for people with similar number of lines of credit.</li>
<li>We estimate a 0.02% lower average interest rate associated with having one additional line of credit, for people with the same bankruptcy history.</li>
</ul>
</section>
<section id="regressing-interest-rate-on-bankruptcy-and-credit-lines-3" class="slide level2">
<h2>Regressing interest rate on bankruptcy and credit lines</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-label="1"></a><span class="fu">ggplot</span>(loans, <span class="fu">aes</span>(<span class="at">x =</span> total_credit_lines, <span class="at">y =</span> interest_rate, <span class="at">color =</span> bankruptcy)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="" aria-label="2"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="" aria-label="3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-07a-multiple-linear-regression_files/figure-revealjs/unnamed-chunk-25-1.png" width="960"></p>
</figure>
</div>
</div>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lec-07a-multiple-linear-regression_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>